version: '3.3'

services:
  db:
    image: postgres:14.1-alpine
    container_name: source_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  db1:
    image: postgres:14.1-alpine
    container_name: target_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  

volumes:
  db:
    driver: local
