server:
  port: 8085

## Target Database Properties
spring:
  data:
  datasource:
    url: jdbc:postgresql://localhost:5432/debperformans
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

## Source Database Properties
debezium:
  datasource:
    host: 127.0.0.1
    port: 5433
    database: debmpys
    username: postgres
    password: postgres